services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: churn-api
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: churn-web
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./reports:/app/reports   # <--- monta a pasta reports no container
